
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
  namespace: sn-labs-fbi1
spec:
  workspaces:
    - name: output
  steps:
    - name: cleanup
      image: alpine:3.19
      script: |
        #!/bin/sh
        set -eux
        rm -rf "$(workspaces.output.path)"/* || true
        mkdir -p "$(workspaces.output.path)"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: eslint
  namespace: sn-labs-fbi1
spec:
  params:
    - name: workingDir
      type: string
      default: $(workspaces.output.path)
    - name: extraArgs
      type: string
      default: "--max-warnings=0"
  workspaces:
    - name: output
  steps:
    - name: install
      image: node:20-alpine
      workingDir: $(params.workingDir)
      script: |
        #!/bin/sh
        set -eux
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
    - name: lint
      image: node:20-alpine
      workingDir: $(params.workingDir)
      script: |
        #!/bin/sh
        set -eux
        npm run lint $(params.extraArgs)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jest-test
  namespace: sn-labs-fbi1
spec:
  params:
    - name: workingDir
      type: string
      default: $(workspaces.output.path)
    - name: script
      type: string
      default: "npm test -- --ci"
  workspaces:
    - name: output
  steps:
    - name: install
      image: node:20-alpine
      workingDir: $(params.workingDir)
      script: |
        #!/bin/sh
        set -eux
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
    - name: test
      image: node:20-alpine
      workingDir: $(params.workingDir)
      script: |
        #!/bin/sh
        set -eux
        $(params.script)